#!/bin/sh

# PROVIDE: freefsm
# REQUIRE: LOGIN postgresql
# KEYWORD: shutdown

. /etc/rc.subr

name="freefsm"
rcvar="freefsm_enable"

command="/usr/local/bin/freefsm"
command_args="-log /var/log/freefsm.log"
pidfile="/var/run/${name}.pid"
required_files="${command}"
start_precmd="${name}_prestart"

freefsm_config="/usr/local/etc/freefsm.conf"

freefsm_prestart()
{
    if [ -f "${freefsm_config}" ]; then
        . "${freefsm_config}"
        export DATABASE_URL SESSION_SECRET PORT ENV STATIC_PATH SETUP_TOKEN
    fi

    if [ ! -f /var/log/freefsm.log ]; then
        touch /var/log/freefsm.log
        chown freefsm:freefsm /var/log/freefsm.log
        chmod 644 /var/log/freefsm.log
    fi
}

load_rc_config $name
run_rc_command "$1"
